---
- name: Create Project
  hosts: localhost

  tasks:

    - name: Create Demo DO457 Project
      ansible.controller.project:
        name: "DO457 Demo Project"
        description: "DO457 Demo Hello from Github"
        organization: "Red Hat Training"
        scm_update_on_launch: "no"
        scm_url: https://github.com/tmichett/AAP2_Controller_Demo.git
        scm_type: git
        scm_branch: main
        credential: Travis GH SCM PAT Credential
        controller_username: admin
        controller_password: redhat
        controller_host: https://controller.lab.example.com
        validate_certs: false
        state: present
