---
### Create Ansible Controller Demo
- import_playbook: Create_Organization.yml
- import_playbook: Create_Machine_Creds.yml
# - import_playbook: Create_SCM_Creds.yml
- import_playbook: Create_Project.yml
- import_playbook: Setup_Inventory.yml
- import_playbook: Create_Job_Template.yml
- import_playbook: Create_Job_Template2.yml
- import_playbook: Create_Job_Template_Fail.yml
- import_playbook: Create_Job_Template_Fail_Fix.yml