---
- name: Gather and display facts
  hosts: ios,junos
  gather_facts: true
  tasks:
    - name: Display fact types
      ansible.builtin.debug:
        var: ansible_facts | type_debug

    - name: Display facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Display a Specific Fact
      ansible.builtin.debug:
        msg: I am a specific fact from {{ inventory_hostname }} and I'm the serial number {{ ansible_facts['net_serialnum'] }}.


    - name: Fix Item Based on Conditions
      ansible.builtin.debug:
        msg: I am fixing {{ inventory_hostname }} with a manual command because my version {{ ansible_facts['net_version'] }} has security vulnerabilities that need manually patched.
      when: ansible_facts['net_version'] == "23.1R1.8"





