---
- name: Jinja Filters and Processing
  hosts: localhost
  gather_facts: true
  vars:
    ip_addresses:
      - 192.168.0.1
      - 192.168.55.256
      - 192.5.6.aa
      - 172.25.250.9/24
  tasks:
    - name: Display variable types
      ansible.builtin.debug:
        var: ip_addresses | type_debug

    - name: Display variable values
      ansible.builtin.debug:
        var: ip_addresses

    - name: Display Valid IP Addresses 
      ansible.builtin.debug:
        msg: "{{ item | ansible.utils.ipaddr('host') }} is a valid IP Address"
      loop: "{{ ip_addresses }}"
      when: item | ansible.utils.ipaddr('host')

    - name: Display Non-Valid IP Addresses 
      ansible.builtin.debug:
        msg: "{{ item }} is not a valid IP Address"
      loop: "{{ ip_addresses }}"
      when: item | ansible.utils.ipaddr('host') == False

    - name: Display Valid IP Addresses and Netmask
      ansible.builtin.debug:
        msg: "{{ item | ansible.utils.ipaddr('host') }} is a valid IP Address and has a netmask of {{ item | ansible.utils.ipaddr('netmask') }}"
      loop: "{{ ip_addresses }}"
      when: item | ansible.utils.ipaddr('host')