- name: Hello World Sample Message from VMs
  hosts: vms
  gather_facts: "{{ variable_facts | default('true') }}"
  tasks:
    - name: Hello Message - Demo
      debug:
        msg: "Hello World! I'm a message from {{  inventory_hostname }} and my IP address is {{ ansible_facts['default_ipv4']['address'] }}  !!!!"
       
- name: Gather and display facts for Cisco Network Devices
  hosts: ios
  become: true
  gather_facts: false
  tasks:
    - name: Gather facts using the 'cisco.ios.ios_facts' module
      cisco.ios.ios_facts:
      when: ansible_network_os == 'ios'

    - name: Display ansible_facts
      ansible.builtin.debug:
        msg: "Hello World! I'm a message from {{  inventory_hostname }} and my model is: {{ hostvars[inventory_hostname]['ansible_facts']['net_model'] }}"
