---
- name: Configure SNMP on Juniper managed nodes
  hosts: junos
  gather_facts: false
  tasks:
    - name: Enable netconf service on port 830
      vars:
        ansible_connection: ansible.netcommon.network_cli
      junipernetworks.junos.junos_netconf:
        netconf_port: 830
        state: present

    - name: Configure SNMP settings
      junipernetworks.junos.junos_snmp_server:
        state: merged
        config:
          location: 'Raleigh, NC'
          contact: 'Network Engineering | neteng@company.com'
          communities:
            - name: rocommunity2n4g!
              authorization: read-only
            - name: rwcommunityd7g$v
              authorization: read-write
