---
ansible_network_os: cisco.ios.ios
ansible_connection: ansible.netcommon.network_cli
ansible_become: true
ansible_become_method: enable
ansible_user: student
ansible_ssh_private_key_file: ~/.ssh/lab_rsa
